# Git 2.35.1 for Debian 10-r37 -> https://docs.bitnami.com/tutorials/understand-rolling-tags-containers
FROM bitnami/git:2.35.1-debian-10-r37
LABEL maintainer="sebastian@sommerfeld.io"

USER bitnami:1000
COPY assets/.gitconfig /home/bitnami/.gitconfig
