---
image: docker:stable

stages:
  - verify

yamllint:
  image: registry.gitlab.com/pipeline-components/yamllint:latest
  stage: verify
  script:
    - yamllint .

shell-check:
  image: koalaman/shellcheck-alpine:stable
  stage: verify
  before_script:
    - shellcheck --version
  script:
    - shellcheck src/**/**/**/*.sh
    - shellcheck src/**/**/**/**/*.sh
