== Install
Download and install a fresh link:https://ubuntu.com[Ubuntu] from an iso image:

. Download iso image from https://ubuntu.com/download/desktop
. Create bootable USB stick using the application "Startup Disk Creator" (shipped with Ubuntu) or something else like https://www.balena.io/etcher[Etcher]
. Install the OS on the machine

Once the basic OS is installed, perform the following steps on your machine:

. Choose NVIDIA graphics driver from "Additional Drivers"
. Clone or download this repository to some tmp folder (`git clone https://github.com/sebastian-sommerfeld-io/kobol-config.git`)
. Run `src/main/host/setup/10-configure.sh` -> Basic configuration and .bashrc settings
. Run `src/main/host/setup/20-install.sh` -> Install software packages
. Run `src/main/host/setup/21-install-intellij.sh` -> Install IntelliJ
. Run `src/main/host/setup/90-start-services.sh` -> Start basic services and docker containers which are always running
. Enable Dark Mode
. Add `~/work`, `~/temp` and `~/virtualmachines` to favourites (in File Manager)
. Login to Firefox Sync
. Setup three monitors, Dock position and icon size, add favourite applications to Dock
. Setup Deja Dup Backups for folder "/media/sebastian/USB-1TB/.kobol-backups/deja-dup
. In GNOME Tweaks app
.. Go to "Workspaces" and set "Display handling" to "Workspaces span displays" to be able to scroll through workspaces (desktops) on all screens
.. Go to "Top Bar" and enable "Battery Percentage" and "Week Numbers" for calendar
.. Clone repositories
. Import existing Virtualbox VMs

=== Steam Setup for Windows Games on Linux
. Install Steam
. Enable the Steam Beta Client: Go to Steam -> Settings
. In the account tab, click change in the Steam Beta Update and click on Steam Beta Update
. Enable Steam Play for all games
. Go to Settings -> Steam Play Tab and click "Enable Steam Play for all titles"
. Install the respective games
