---
version: "3.3"
services:

  # Schedule tasks and jobs
  rundeck:
    image: pegasus/rundeck:latest
    container_name: rundeck
    command: -Dserver.http.port=7440
    tty: true
    environment:
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
    volumes:
      - rundeck_data:/home/rundeck/server/data
      - ./assets/rundeck/inventory.yml:/home/rundeck/inventory.yml
      - /home/vagrant/.ssh:/home/rundeck/.ssh:ro
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    ports:
      - 7440:7440

volumes:
  rundeck_data:
