---
pegasus:
  nodename: pegasus
  hostname: pegasus
  description: Vagrantbox Pegasus
  username: vagrant
  osFamily: unix
  node-executor: jsch-ssh
  file-copier: jsch-scp
  tags: Vagrantbox
  osName: Linux
  ssh-keypath: /home/rundeck/.ssh/id_rsa
  #sshport: ??

# https://github.com/rundeck-plugins/openssh-node-execution
prometheus:
  nodename: prometheus
  hostname: prometheus
  description: RasPi
  username: pi
  osFamily: unix
  node-executor: ssh-exec
  file-copier: ssh-exec
  tags: RasPi
  osName: Linux
  ssh-authentication: privatekey
  ssh-key-storage-path: keys/rundeck/raspi-prometheus.key
