---
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 480416a6-ef1b-4163-a386-ec6800033cd0
  loglevel: INFO
  name: Clone Repo kobol-configuration
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
      - description: hostname
        exec: echo "$HOSTNAME"
      - description: cleanup before checkout
        exec: (cd repos || exit && rm -rf kobol-configuration)
      - description: clone repository
        exec: (cd repos || exit && git clone git@gitlab.com:sommerfeld.sebastian/kobol-configuration.git)
      - description: create branch
        exec: (cd repos/kobol-configuration || exit && git branch feat/rundeck-test)
      - description: checkout branch
        exec: (cd repos/kobol-configuration || exit && git checkout feat/rundeck-test)
      - description: create file
        exec: (cd repos/kobol-configuration || exit && echo "= Test from Rundeck" >
          rundeck.adoc)
      - description: push to remote repo
        exec: (cd repos/kobol-configuration || exit && git add * && git commit -m rundeck && git push --set-upstream origin feat/rundeck-test)
    keepgoing: false
    strategy: node-first
  uuid: 480416a6-ef1b-4163-a386-ec6800033cd0
